#define idsIMPORTDATABASE            101
#define idsOPENPASSWORD              112
#define idsABOUT                     6166
#define idsTOTD                      6167
#define idsMAILDOWNLOAD              6182
#define idsBINMAIL                   6185
#define idsMAILDIR                   6186
#define idsMAILERASE                 6187
#define idsSIGNATURE                 6191
#define idsOUTBASKET                 6195
#define idsSAYEDITOR                 6200
#define idsMODEMSETTINGS             6205
#define idsGOTO                      6208
#define idsJOINHOST                  6210
#define idsFIND                      6212
#define idsSCRPAD_EXPORT             6216
#define idsFDL                       6219
#define idsFILELIST                  6220
#define idsCOMMENTEDITOR             6223
#define idsSCRIPT                    6228
#define idsSCRIPTEDIT                6229
#define idsFUL                       6231
#define idsINPUT                     6232
#define idsRESUMELIST                6243
#define idsFILENAMECVT               6272
#define idsFINDONE                   6273
#define idsGETRESUME                 6280
#define idsBANPAR                    6281
#define idsUNBANPAR                  6282
#define idsEVENTLOG                  6300
#define idsLOCALTOPIC                6303
#define idsPARLIST                   6306
#define idsEVENTLOGOPTIONS           6318
#define idsSAVEMODEMSETTINGS         6321
#define idsADDPAR                    6325
#define idsNEWSIG                    6326
#define idsPAGESETUP_MARGINS         6329
#define idsCOMOD                     6342
#define idsIMPORT                    6345
#define idsREADSCRATCHPAD            6348
#define idsMAILRENAME                6369
#define idsMAILEXPORT                6376
#define idsLOGIN                     6390
#define idsSPELLCHECK                6400
#define idsRESIGN                    6407
#define idsCTSLOWERROR               6412
#define idsTERMINALCONNECT           6413
#define idsFDLPROMPT                 6418
#define idsTERMINAL_OPTIONS          6425
#define idsTERMINAL_FONT             6426
#define idsTERMINAL_COLOURS          6427
#define idsTERMINAL_EMULATIONS       6428
#define idsGETNEWNEWSGROUPS          6431
#define idsSUBSCRIBE                 6432
#define idsNEWCONNECT_P1             6443
#define idsNEWCONNECT_P2             6444
#define idsNEWS_GENERAL              6454
#define idsPREF_SPELLING             6455
#define idsRULEMANAGER               6456
#define idsEDITRULE                  6457
#define idsFORUMPICKER               6458
#define idsPREF_GENERAL              6459
#define idsCUSTOMISE_KEYBOARD        6463
#define idsIBP_DATABASE              6464
#define idsIBP_PURGE                 6465
#define idsIBP_FOLDER                6466
#define idsIBP_TOPIC                 6467
#define idsSETUPWIZ_P1               6474
#define idsSETUPWIZ_P2               6475
#define idsSETUPWIZ_P3               6476
#define idsSETUPWIZ_P4               6477
#define idsSETUPWIZ_P5               6478
#define idsSETUPWIZ_P6               6473
#define idsSETUPWIZ_P6_1             6472
#define idsSETUPWIZ_P7               6479
#define idsSETUPWIZ_P8               6480
#define idsDECODEFILENAME            6481
#define idsCUSTOMISE_COLOURS         6482
#define idsGETNEWHEADERS             6483
#define idsGETTAGGEDARTICLES         6484
#define idsMANUALDECODE              6485
#define idsPREF_VIEWER               6486
#define idsFORWARDMAIL               6489
#define idsNEWSGROUPSFILTER          6490
#define idsPAGESETUP_HEADERS         6491
#define idsPREF_ATTACHMENTS          6492
#define idsPREF_READING              6494
#define idsPOP3LOGIN                 6497
#define idsPREF_CIX                  6498
#define idsSCHEDULER                 6499
#define idsTOOLBAR_CONFIG            6500
#define idsSAVESEARCH                6513
#define idsMAILBOX                   6516
#define idsADDONS                    6523
#define idsADDON_PROPERTIES          6524
#define idsADMIN                     6543
#define idsADDUSER                   6544
#define idsEDITUSER                  6545
#define idsMAILEDITOR                6550
#define idsARTICLEEDITOR             6551
#define idsEXPORT                    6552
#define idsGRPLIST_ALL               6555
#define idsIBP_SIGNATURE             6556
#define idsUSERLIST_ALL              6557
#define idsCIXLIST_ALL               6558
#define idsIBP_RULES                 6559
#define idsPREF_PURGE                6565
#define idsMODEMCONNECTIONSCARD      6571
#define idsIPCONNECTIONSCARD         6572
#define idsPREF_RAS                  6574
#define idsPRINTMSG                  6576
#define idsPRINTTERMINAL             6577
#define idsPREF_DIRASSOC             6579
#define idsPREF_DIRECTORIES          6580
#define idsIBP_MODERATORS            6583
#define idsIBP_SETTINGS              6584
#define idsPRINTCOMPOSING            6585
#define idsPREF_MAIL                 6586
#define idsNEWCONNCARD1              6587
#define idsNEWCONNCARD2              6588
#define idsNEWCONNCARD3              6589
#define idsNEWCONNCARD4              6590
#define idsNEWCONNCARD5              6591
#define idsIBP_ABOUT                 6592
#define idsREPORT                    6612
#define idsFILELISTFIND              6613
#define idsRESUMES                   6614
#define idsMUGSHOTEDIT               6615
#define idsPRINTRESUME               6616
#define idsEDITRESUME                6617
#define idsBLINK                     6618
#define idsCUSTOMISE_FONTS           6619
#define idsEXTAPP                    6626
#define idsPRINTFILELIST             6627
#define idsPREF_BROWSER              6628
#define idsPREF_INTERNET             6636
#define idsNEWBLINKENTRY             6637
#define idsPREF_SMTP                 6638
#define idsBLINK_CIX                 6640
#define idsBLINK_IP                  6641
#define idsINBASKET                  6643
#define idsPAGESETUP_FONT            6644
#define idsBLINK_RAS                 6645
#define idsPREF_DELIVERY             6646
#define idsPRINTPARLIST              6647
#define idsNOTICEBOARDPROMPT         6649
#define idsSCHEDEDIT                 6650
#define idsIBP_SERVER                6651
#define idsFLISTFIND                 6654
#define idsNEWS_DELIVERY             6655
#define idsNEWS_HEADERS              6659
#define idsBUTTONBITMAP              6660
#define idsNEWCONNCARD6              6661
#define idsMISSEDSCHEDULE            6663
#define idsPREF_EDITOR               6665
#define idsSORTMAILFROM              6674
#define idsSORTMAILTO                6675
#define idsCIXSETTINGS               6676
#define idsNEWS_SERVERS              6677
#define idsNEWS_PROPERTIES_CIX       6678
#define idsNEWS_PROPERTIES_IP        6679
#define idsMAIL_HEADERS              6680
#define idsPURGESETTINGS             6681
#define idsCOMM_CARD                 6682
#define idsCOMM_BLINK                6683
#define idsNEWCONNCARD2_TAPI         6684
#define idsIMPORTWIZARD              6686
#define idsMESSAGEWINDOW             6687
#define idsMISSINGDB                 6688
#define idsCOPYMSG                   6689
#define idsMOVEMSG                   6690
#define idsTAPIMODEMCONNECTIONSCARD  6691
#define idsGRPLIST_NEW               6692
#define idsUSERLIST_NEW              6693
#define idsCIXLIST_NEW               6694
#define idsTOOLBAR_OPTIONS           6695
#define idsNEWCONNCARD6_TAPI         6696
#define idsNEWCONNCARD1a             6699
#define idsSTARTWIZ                  6700 
#define idsREPORTPROMPT              6701
#define idsPRINTLIST                 6702
#define idsPRINTINBASKET             6703
#define idsPRINTOUTBASKET            6704
#define idsADDRVIEW                  7000
#define idsADDRPICKER                7001
#define idsADDREDIT                  7002
#define idsPGPKEY                    7003
#define idsPICTURE                   7004
#define idsEDITGROUP                 7005
#define idsEDITADDRBOOK              7006
#define idsPASSWORD                  7007
#define idsIBP_MAIL                  7010
#define idsCHECKANDREPAIR            8000
#define idsCONFPICKER                8001
#define idsRECOVERSCRATCHPAD         8002
#define idsQUERYRECOVER              8003
#define idsCHANGEDIR                 9000
